# Generated by Django 4.2.14 on 2024-07-25 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_user_groups_alter_user_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="company",
        ),
        migrations.DeleteModel(
            name="Company",
        ),
    ]
