# Generated by Django 4.2.14 on 2024-07-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_remove_user_company_delete_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(db_comment="사용자 이름", max_length=200),
        ),
    ]
