# Generated by Django 4.2.14 on 2024-07-23 01:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reserved_datetime",
                    models.DateTimeField(db_comment="예약 일시"),
                ),
                (
                    "reserved_count",
                    models.PositiveIntegerField(
                        db_comment="예약 인원 수",
                        validators=[
                            django.core.validators.MaxValueValidator(50000)
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PEND", "pending"), ("RSVD", "reserved")],
                        db_comment="예약 상태",
                        default="PEND",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="예약한 사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
