# Generated by Django 4.2.14 on 2024-07-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["reserved_datetime"]},
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["reserved_datetime", "status"],
                name="reservation_reserve_bbae10_idx",
            ),
        ),
    ]
