# Generated by Django 4.2.14 on 2024-07-24 02:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reservation", "0002_alter_reservation_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="생성 일시"
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, db_comment="수정 일시"),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(db_comment="시험 시작 일시"),
                ),
                ("end_datetime", models.DateTimeField(db_comment="시험 끝 일시")),
                (
                    "max_capacity",
                    models.PositiveIntegerField(
                        db_comment="최대 예약 인원",
                        default=50000,
                        validators=[
                            django.core.validators.MaxValueValidator(50000)
                        ],
                    ),
                ),
                (
                    "confirmed_reserved_count",
                    models.IntegerField(
                        db_comment="확정된 예약 인원",
                        default=0,
                        validators=[
                            django.core.validators.MaxValueValidator(50000)
                        ],
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="reservation",
            name="reservation_reserve_bbae10_idx",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="reserved_datetime",
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PEND", "pending"),
                    ("RSVD", "reserved"),
                    ("CNCL", "canceled"),
                ],
                db_comment="예약 상태",
                default="PEND",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                db_comment="예약한 사용자",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["status"], name="reservation_status_af75b6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                check=models.Q(("reserved_count__lte", 50000)),
                name="reserved_count_max_value_check",
            ),
        ),
        migrations.AddIndex(
            model_name="examschedule",
            index=models.Index(
                fields=["start_datetime"],
                name="reservation_start_d_81626c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="examschedule",
            index=models.Index(
                fields=["end_datetime"], name="reservation_end_dat_4f9a88_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="examschedule",
            constraint=models.CheckConstraint(
                check=models.Q(("confirmed_reserved_count__lte", 50000)),
                name="confirmed_reserved_count_max_value_check",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="exam_schedule",
            field=models.ForeignKey(
                db_comment="시험 일정",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="reservation.examschedule",
            ),
            preserve_default=False,
        ),
    ]
