# Generated by Django 4.2.14 on 2024-07-24 02:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        (
            "reservation",
            "0003_examschedule_alter_reservation_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="created_datetime",
            field=models.DateTimeField(
                auto_now_add=True,
                db_comment="생성 일시",
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="updated_datetime",
            field=models.DateTimeField(auto_now=True, db_comment="수정 일시"),
        ),
    ]
