# Generated by Django 4.2.14 on 2024-07-24 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0004_reservation_created_datetime_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="examschedule",
            unique_together={("start_datetime", "end_datetime")},
        ),
    ]
